print("What is your name, human?")
name = input()
print("How old are you? (in years)")
age = int(input())
print("How tall are you (in m)?")
height = float(input())
print("How much do you weight(in kg)?")
weight = float(input())
bmi = weight/(height**2)
print(f"{name} your are {age} old. Your BMI is {bmi:.2f}")