print("Enter the number of lives")
life = int(input())
print("Enter the energy level")
energy = int(input())
print("Enter the shield level")
shield = int(input())
print("Health has been set")
print("Lives: ", "\u2665"*life)
print("Energy: ", "\u2666"*energy)
print("Shield: ", "\u2666"*shield)